export const Deliverylist=[
    {
        "title": "Lorem",
        "bg": "linear-gradient(45deg, #dd2476, #ff512f)",
        "color": "#0072ff",
        "id":1,
        "date": "2020-05-01",
        "time": "10:00",
        "location": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "deliveryStatus": "Pending",
        "customer": "John Doe",
        "phone": "1234567890",
        "paymentStatus": "Pending",
        "paymentMethod": "Cash",
        "total": "1000",
        
    },
    {
        "title": "Lorem",
        "bg": "linear-gradient(45deg, #dd2476, #ff512f)",
        "color": "#ff512f",
        "id":2,
        "date": "2020-05-01",
        "time": "10:00",
        "location": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "deliveryStatus": "Pending",
        "customer": "John Doe",
        "phone": "1234567890",
        "paymentStatus": "Pending",
        "paymentMethod": "Cash",
        "total": "1000",
        
    },
    {
        "title": "Lorem",
        "bg": "linear-gradient(45deg, #dd2476, #ff512f)",
        // "bg": "linear-gradient(45deg, #11998e, #38ef7d)",
        "color": "#38ef7d",
        "id":3,
        "date": "2020-05-01",
        "time": "10:00",
        "location": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "deliveryStatus": "Pending",
        "customer": "John Doe",
        "phone": "1234567890",
        "paymentStatus": "Pending",
        "paymentMethod": "Cash",
        "total": "1000",
        
    },
    {
        "title": "lorem",
        "bg": "linear-gradient(45deg, #dd2476, #ff512f)",
        "color": "#e100ff",
        "id":4,
        "date": "2020-05-01",
        "time": "10:00",
        "location": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "deliveryStatus": "Pending",
        "customer": "John Doe",
        "phone": "1234567890",
        "paymentStatus": "Pending",
        "paymentMethod": "Cash",
        "total": "1000",
    },
]